### ISSUE TITLE
build on windows

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#27]
I'm currently investigating cli build failures on Windows, and realized sdk-js doesn't test there yet. Travis has windows available:

```yml
os:
  - linux
  - windows
```

And this is what the cli is currenlty doing using github actions:

```yml
name: Node CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use latest npm
      run: npm install -g npm@latest
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
```

If we add tests here we can gain more confidence in cross OS support and help troubleshooting as well.
